### PR TITLE
Added support for md5-based fingerprinting mentioned in #9

### PR DESCRIPTION
**Pull request by inca**
@ReedD Could you please verify that everything works as expected in your environment? TIA

### CODE REVIEW

**Comment by xizhao** [comment]
Any updates on this?

**Comment by inca** [comment]
This PR is pending for at least half-year now. It doesn't sound like this repo is maintained :neutral_face:

**Comment by ReedD** [comment]
Sorry guys! I totally forgot about this PR.

**Comment by inca** [comment]
Thanks :)

**Comment by ReedD** [comment]
And I just pushed 1.2 to npm.

**Comment by ReedD** [comment]
@inca people are reporting issues with your pull request, any ideas? Issue #12 .

**Comment by BridgeAR** [comment]
Please revert this commit until you find a solution and push 1.2.1. Anyone depending on this library is going to run into quite some trouble debugging this. The standard for npm is to accept all minor updates, since they should not break anything. So most people use this notation for most of there dependencies.

**Comment by ReedD** [comment]
Reverted.

**Pull request merged**
